# syntax=docker/dockerfile:1.7
# rct-hub — Next.js standalone deployment
#
# Build:
#   docker build \
#     --build-arg NEXT_PUBLIC_API_BASE=https://api.example.com \
#     --build-arg NEXT_PUBLIC_WS_BASE=wss://api.example.com \
#     --build-arg NEXT_PUBLIC_SITE_URL=https://www.example.com \
#     -t rct-hub:prod .
#
# Run:
#   docker run --rm -p 3000:3000 -e PORT=3000 -e HOSTNAME=0.0.0.0 rct-hub:prod
#
# Configuration: NEXT_PUBLIC_* values are baked at build time (Next.js inlines
# them into the client bundle). If you need to change them later, rebuild.

ARG NEXT_PUBLIC_API_BASE=http://localhost:8080
ARG NEXT_PUBLIC_WS_BASE=ws://localhost:8080
ARG NEXT_PUBLIC_SITE_URL=http://localhost:3000

# ---------- deps stage ----------
FROM node:22-alpine AS deps
WORKDIR /app

# Install only lockfile deps; copies happen in the build stage.
COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml* ./
RUN corepack enable && \
    if [ -f pnpm-lock.yaml ]; then \
        pnpm config set fetch-retries 5 && \
        pnpm install --frozen-lockfile --prod=false; \
    else \
        npm install; \
    fi

# ---------- build stage ----------
FROM node:22-alpine AS build
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Public env vars must be present at build time. They get inlined into the
# client bundle by Next.js; you cannot change them at runtime.
ARG NEXT_PUBLIC_API_BASE
ARG NEXT_PUBLIC_WS_BASE
ARG NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE} \
    NEXT_PUBLIC_WS_BASE=${NEXT_PUBLIC_WS_BASE} \
    NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}

RUN corepack enable && pnpm build

# ---------- runtime stage ----------
# Use alpine for the shell needed by `node` server runtime hooks (`.next/standalone`
# references relative paths; copying them carefully is the cleanest approach).
FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production \
    PORT=3000 \
    HOSTNAME=0.0.0.0 \
    NEXT_TELEMETRY_DISABLED=1

# Copy only what's needed: server.js + the per-route node_modules chunks +
# public/ + .next/static. Standalone emits these under .next/standalone/.
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/public ./public
COPY --from=build /app/.next/static ./.next/static

EXPOSE 3000

# Standalone server.js is generated by Next.js with the project's name field
# (here: "rct-hub"). It listens on PORT (default 3000).
CMD ["node", "server.js"]
